export {
  generatePath,
  Prompt,
  MemoryRouter,
  RedirectProps,
  Redirect,
  RouteComponentProps,
  RouteProps,
  Route,
  BrowserRouter as Router,
  StaticRouter,
  Switch,
  match,
  matchPath,
  withRouter,
  RouterChildContext,
} from 'react-router-dom'
